services:
  backend:
    build: .
    container_name: expert_rating_backend_dev
    restart: always
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    entrypoint: /usr/local/bin/docker-entrypoint-backend.sh
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./migrations:/app/migrations
      - ./alembic.ini:/app/alembic.ini
      - ./logs:/app/logs
    depends_on:
      - redis
      - db

  redis:
    image: redis:7-alpine
    container_name: expert_rating_redis_dev
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data

  db:
    image: mysql:8.0
    container_name: expert_rating_mysql_dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword # Пароль для суперпользователя
      MYSQL_DATABASE: expert_rating_dev # Название базы данных для приложения
      MYSQL_USER: devuser # Пользователь для приложения
      MYSQL_PASSWORD: devpass # Пароль для пользователя приложения
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql

volumes:
  redis_data_dev:
  mysql_data_dev: